# Generated by Django 5.0.7 on 2024-10-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeriaproducto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=8)),
                ('asunto', models.CharField(max_length=100)),
            ],
        ),
    ]
