# Generated by Django 5.0.7 on 2024-10-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeriaproducto', '0002_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
