# Generated by Django 5.1.2 on 2024-10-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeriaproducto', '0003_alter_cita_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_hora',
            field=models.DateTimeField(null=True),
        ),
    ]
