# Generated by Django 5.1.2 on 2024-11-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeriaproducto', '0004_cita_fecha_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='portafolio/')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
